export const PLANT_CREATION_GUIDE = `Sprout plant creation rules:
- Generate a declarative plant specification only. Never emit TypeScript, JSX, executable code, imports, functions, URLs, or external asset links.
- Sprout uses a 400 by 400 native React Native SVG canvas. Keep anchors between 20 and 380 so foliage, blooms, particles, pot, and aura are properly framed.
- Geometry families include: tree, stalk, vine, radial_bloom, blossom_cluster, radial_leaf, pothos_leaf, cactus_arm, orchid_bloom, rose_bloom, sakura_cluster, sunflower_head, spider_leaf, decorative_shape, face, accessory, and custom_path.
- Set generationMetadata.archetype to one of: tree, shrub, vine, cactus_succulent, flowering, leafy, fantasy_hybrid, floating_island, bioluminescent_fungi, crystal_spire, terrarium_jar, or elemental_spirit. Match the user's creative prompt intent.
- Pot styles include: classic, rounded, none, floating_island, terrarium_jar, and crystal_base. For floating islands, crystal spires, or magical terrariums, use matching potStyle values to create an un-formulaic base.
- Enhance visual depth with multi-stop gradients: use layer.gradient with type ("linear" | "radial"), 2-4 color stops, and angle for glowing stems, cosmic leaves, or bioluminescent caps.
- Add ambient atmosphere with layer.particles: set type ("spores" | "sparkles" | "fireflies" | "petals" | "runes"), count (4-25), color, and spreadRadius.
- For unique or alien motifs, use layer type custom_path and provide pathData (e.g. SVG path string starting with M/C/Q/L/Z) for custom spiral vines, crystal facets, or organic fronds.
- Compose a visually striking, mature specimen with 8-22 purposeful layers and varied zIndex layers to avoid flat or repetitive formulaic layouts.
- Suggest an original plant name and description. Avoid direct reproductions of copyrighted characters.`;
